PATCH http://localhost:4000/api/v1/animal-feeding/products/673dd758d17020f4ea31d5e1 HTTP/1.1

Content-Type: application/json


{
  "name": "shudu",
  "description": "just description",
  "price": 25000,
  "quantity": 23,
  "category": "animal-feeding"
}