// responseStatusCode.js

// 200
const CREATED = 201;
const OK = 200;

// 400
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;

// 500
const SERVER_ERROR = 500;
const INTERNAL_SERVER_ERROR = 500;

// NO CONTENT
const NO_CONTENT = 204;

module.exports = {
  CREATED,
  OK,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  SERVER_ERROR,
  INTERNAL_SERVER_ERROR,
  NO_CONTENT
};
